---
server:

  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"

  adminAPI:
    enabled: true

engine:
  defaultPolicyVersion: "default"

auxData:
  jwt:
    disableVerification: true

storage:
  driver: "postgres"
  postgres:
    url: "postgres://sa:pwd@macarons:5432/postgres?sslmode=disable&search_path=cerbos"
