GET http://localhost:8000/health-check

POST http://localhost:8000/accounts/token
Content-Type: application/json

{
    "secret": "zMEdizE0f4A-htl9MLS4jBFbmtCPo_oA1sZOajTd0O-rQ",
    "grantType": "master"
}

POST http://localhost:8000/hello_rocket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDcwMTkzMDIsImV4cCI6MTc0NzAyMjkwMiwic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.OkhMVkJKj7u-QigCzETHUF45zoAzqQ09zzrMrAQNyRG8R8kbFVQW4Pt0PguiwHpLhStRyfwHuHAnN9SEtXE_tcwn2RKPYuEcKwh9o141Y2Xy0_glQ0U8mJK2HYtM_djqD_NQIVXfBPN50Uw9mMi59W0lcF5ojJbdQnqmlrxTKtjbkFDec1EjrlrKenP0bxb5w5iZdcsUQVwI9ddcxPK-JroyX2rKCfwY2rG0DPYJ_xX91pcYa6o1dch8IFyQ33C3VF8RLEgr4sCHFVdkQUgb6L8_oKHjbpnfxlGrbo3kuvFU7JBUZQGD3s6Y2x7xEBZiw_iE1hc4M_SKOkCyapUnmg

{
    "name": "Hello Rocket",
    "description": "Hello Rocket Application"
}

POST http://localhost:8000/hello_rocket/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDcwMTkzMDIsImV4cCI6MTc0NzAyMjkwMiwic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.OkhMVkJKj7u-QigCzETHUF45zoAzqQ09zzrMrAQNyRG8R8kbFVQW4Pt0PguiwHpLhStRyfwHuHAnN9SEtXE_tcwn2RKPYuEcKwh9o141Y2Xy0_glQ0U8mJK2HYtM_djqD_NQIVXfBPN50Uw9mMi59W0lcF5ojJbdQnqmlrxTKtjbkFDec1EjrlrKenP0bxb5w5iZdcsUQVwI9ddcxPK-JroyX2rKCfwY2rG0DPYJ_xX91pcYa6o1dch8IFyQ33C3VF8RLEgr4sCHFVdkQUgb6L8_oKHjbpnfxlGrbo3kuvFU7JBUZQGD3s6Y2x7xEBZiw_iE1hc4M_SKOkCyapUnmg

{
    "name": "My first task"
}

