GET http://localhost:8000/health-check

POST http://localhost:8000/accounts/token
Content-Type: application/json

{
    "secret": "zMEdizE0f4A-htl9MLS4jBFbmtCPo_oA1sZOajTd0O-rQ",
    "grantType": "master"
}

POST http://localhost:8000/hello_rocket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDczMjcyMzYsImV4cCI6MTc0NzMzMDgzNiwic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.hB7ArnYrubTPY5u4MnHmKHeMAH9POSW1NjnzNWJ7Qqht8VLKAava-BcWqzKY8hcwlMhoaazVInimp5ZpBRezg7oGsV2KPUAy2MBAUWtAXJv8fbXKdlDGDOj68kT3Qm6Q9YOb5V4UZu2K3D-Qnridg4mEq7kRzk3u0DSa0z3XOztMxlf9eAnyoJiqtEFur6NPWh3Pyw5gh68_7Wy0CG5juSrKeErRJfjOeLV44UjJ1RhO_Foi6CuNbDbqZPk3jU3TVgpPZ4F9Iza7wmcyxV0qWZ5eaR2ZGQ1zHzF04lqpZIXwKCCin1F599ENHIB1aZvfy3LR_3v5URi2X-LMYPBwzA

{
    "name": "Hello Rocket",
    "description": "Hello Rocket Application"
}

POST http://localhost:8000/hello_rocket/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDczMjcyMzYsImV4cCI6MTc0NzMzMDgzNiwic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.hB7ArnYrubTPY5u4MnHmKHeMAH9POSW1NjnzNWJ7Qqht8VLKAava-BcWqzKY8hcwlMhoaazVInimp5ZpBRezg7oGsV2KPUAy2MBAUWtAXJv8fbXKdlDGDOj68kT3Qm6Q9YOb5V4UZu2K3D-Qnridg4mEq7kRzk3u0DSa0z3XOztMxlf9eAnyoJiqtEFur6NPWh3Pyw5gh68_7Wy0CG5juSrKeErRJfjOeLV44UjJ1RhO_Foi6CuNbDbqZPk3jU3TVgpPZ4F9Iza7wmcyxV0qWZ5eaR2ZGQ1zHzF04lqpZIXwKCCin1F599ENHIB1aZvfy3LR_3v5URi2X-LMYPBwzA

{
    "name": "My first task"
}


GET http://localhost:8000/hello_rocket/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDczMzEwMDUsImV4cCI6MTc0NzMzNDYwNSwic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.Dm0tkqOVW8-yTIYShm4moq1w6GnZp4qHr-Uk9VmUUqcsjRQnglo4msf-3AzORcG47dn27aT8Zr0RzTt5P3lR1PuuqUIXarYG2rJrG0pn7azfAXU51KYYI708GqiGlTGXVyvT2M7Cc77xpOOaa4gor78EyTwMXRSyC7qI16AIqQoo38yGj83ESLl-gFpOER5zykRAywA7xWYdB2V1WiR0_vQx9HsBg2VTA0khX-wHuc3g4JT_wmpEqYqUMaqyKUasg1sf9Osl5W9jFK0u1e8AVUl4iQ4PudRLkq_Tb_LmM4bKcBYvl96_tBlu0IA1CmSsciuqOYB8C3ILrIaHySQEnA

POST http://localhost:8000/hello_rocket/task/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDczMzEwMDUsImV4cCI6MTc0NzMzNDYwNSwic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.Dm0tkqOVW8-yTIYShm4moq1w6GnZp4qHr-Uk9VmUUqcsjRQnglo4msf-3AzORcG47dn27aT8Zr0RzTt5P3lR1PuuqUIXarYG2rJrG0pn7azfAXU51KYYI708GqiGlTGXVyvT2M7Cc77xpOOaa4gor78EyTwMXRSyC7qI16AIqQoo38yGj83ESLl-gFpOER5zykRAywA7xWYdB2V1WiR0_vQx9HsBg2VTA0khX-wHuc3g4JT_wmpEqYqUMaqyKUasg1sf9Osl5W9jFK0u1e8AVUl4iQ4PudRLkq_Tb_LmM4bKcBYvl96_tBlu0IA1CmSsciuqOYB8C3ILrIaHySQEnA

{

}