GET http://localhost:8000/health-check

POST http://localhost:8000/accounts/token
Content-Type: application/json

{
    "secret": "zMEdizE0f4A-htl9MLS4jBFbmtCPo_oA1sZOajTd0O-rQ",
    "grantType": "master"
}

POST http://localhost:8000/hello_rocket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDcxOTI1MTcsImV4cCI6MTc0NzE5NjExNywic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.KPQMmLx5CyAUfV1cDpsnc8DOvEcLD5XpbNrJrUy9Htiv07Z1qxOSMlvI08TejEEOZPAqf2Mf54E-dcazb-sLDIGgCjMETVEUU5NVxtZczPrl5TdJYvJ23uzONUyIqD0aKHh9LcMNE57Cp2NQ_gifjeSeya6J1ZMSRLSvwm2d_B0EYlIVI-YouzzB_dQLe247wS4B3htJcwwMklyKsEMFDj9aG4HrDcp20mP4xksUI58URt5RWzBEwZ_9uDiLqU2crXYaWeLON_yUyYVrMYVkMihUUEUX5wvxNOPbKdQFjYQ4HrFwb_ggHta6B7vo9dPzmRG1Jfy6YtGwT3kF1wCxcQ

{
    "name": "Hello Rocket",
    "description": "Hello Rocket Application"
}

POST http://localhost:8000/hello_rocket/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDcxOTI1MTcsImV4cCI6MTc0NzE5NjExNywic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.KPQMmLx5CyAUfV1cDpsnc8DOvEcLD5XpbNrJrUy9Htiv07Z1qxOSMlvI08TejEEOZPAqf2Mf54E-dcazb-sLDIGgCjMETVEUU5NVxtZczPrl5TdJYvJ23uzONUyIqD0aKHh9LcMNE57Cp2NQ_gifjeSeya6J1ZMSRLSvwm2d_B0EYlIVI-YouzzB_dQLe247wS4B3htJcwwMklyKsEMFDj9aG4HrDcp20mP4xksUI58URt5RWzBEwZ_9uDiLqU2crXYaWeLON_yUyYVrMYVkMihUUEUX5wvxNOPbKdQFjYQ4HrFwb_ggHta6B7vo9dPzmRG1Jfy6YtGwT3kF1wCxcQ

{
    "name": "My first task"
}


GET http://localhost:8000/hello_rocket/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDcxOTI1MTcsImV4cCI6MTc0NzE5NjExNywic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.KPQMmLx5CyAUfV1cDpsnc8DOvEcLD5XpbNrJrUy9Htiv07Z1qxOSMlvI08TejEEOZPAqf2Mf54E-dcazb-sLDIGgCjMETVEUU5NVxtZczPrl5TdJYvJ23uzONUyIqD0aKHh9LcMNE57Cp2NQ_gifjeSeya6J1ZMSRLSvwm2d_B0EYlIVI-YouzzB_dQLe247wS4B3htJcwwMklyKsEMFDj9aG4HrDcp20mP4xksUI58URt5RWzBEwZ_9uDiLqU2crXYaWeLON_yUyYVrMYVkMihUUEUX5wvxNOPbKdQFjYQ4HrFwb_ggHta6B7vo9dPzmRG1Jfy6YtGwT3kF1wCxcQ

POST http://localhost:8000/hello_rocket/task/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImlzcyI6InNlbGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoibWFzdGVyLWFjY291bnQiLCJhdWQiOiJodHRwczovL3JvY2tldC1hcGkucGFyYW5vaWQuc29mdHdhcmUiLCJpYXQiOjE3NDcxOTI1MTcsImV4cCI6MTc0NzE5NjExNywic2NvcGUiOiJyZWFkOmFjY291bnRzIGNyZWF0ZTphY2NvdW50cyBtb2RpZnk6YWNjb3VudHMtc2NvcGUgbW9kaWZ5OmFjY291bnRzLWFwcGxpY2F0aW9ucy1zY29wZSBkZWxldGU6YWNjb3VudHMgcmVhZDphcHBsaWNhdGlvbnMgY3JlYXRlOmFwcGxpY2F0aW9ucyBtb2RpZnk6YXBwbGljYXRpb25zIGRlbGV0ZTphcHBsaWNhdGlvbnMgcmVhZDpvYmplY3RzLW1ldGEgbW9kaWZ5Om9iamVjdHMtbWV0YSByZWFkOm9iamVjdHMgY3JlYXRlOm9iamVjdHMgbW9kaWZ5Om9iamVjdHMgZGVsZXRlOm9iamVjdHMifQ.KPQMmLx5CyAUfV1cDpsnc8DOvEcLD5XpbNrJrUy9Htiv07Z1qxOSMlvI08TejEEOZPAqf2Mf54E-dcazb-sLDIGgCjMETVEUU5NVxtZczPrl5TdJYvJ23uzONUyIqD0aKHh9LcMNE57Cp2NQ_gifjeSeya6J1ZMSRLSvwm2d_B0EYlIVI-YouzzB_dQLe247wS4B3htJcwwMklyKsEMFDj9aG4HrDcp20mP4xksUI58URt5RWzBEwZ_9uDiLqU2crXYaWeLON_yUyYVrMYVkMihUUEUX5wvxNOPbKdQFjYQ4HrFwb_ggHta6B7vo9dPzmRG1Jfy6YtGwT3kF1wCxcQ

{

}